### ISSUE TITLE
Configuration File Is Empty message during test run.

### ISSUE THREAD

**Issue by jesseeuton** [pganalyze/collector#11]
Followed the instructions for setting up an AWS RDS postgres instance (using an Amazon Linux AMI EC2 instance).

I get the following message when I try to do a test run:

E Config Error: Configuration file is empty.  Please edit /etc/pganalyze-collector.conf and reload the collector.

![image](https://cloud.githubusercontent.com/assets/1945500/21368061/f0db73e4-c6bd-11e6-978b-38a41fd1ddf1.png)

I tried reloading the collector and still receive the error.

here is a screenshot of the /etc/pganalyze-collector.conf file (with fake text for this screenshot only).

![image](https://cloud.githubusercontent.com/assets/1945500/21368141/78257728-c6be-11e6-969a-327045d2d723.png)

**Comment by lfittl** [comment]
Hi @jesseeuton - thanks for reaching out!

Can you try removing the comment symbol `#` in front of the lines?

That should resolve the problem :)

**Comment by jesseeuton** [comment]
*sigh*

Glad I could provide something for you guys to laugh at on a Friday afternoon ;)

**Comment by lfittl** [comment]
No worries, it has happened a few times before ;)
