### ISSUE TITLE
[feature request] ability to collect multiple db instances with one docker container

### ISSUE THREAD

**Issue by caleb15** [pganalyze/collector#122]
Readme:
> We currently require one Docker container per RDS instance monitored.

I was very surprised to learn that a docker container can only collect data from one db instance. This seems pretty odd given that non-docker collector can collect from multiple RDS instances.

**Comment by uhoh-itsmaciek** [comment]
Hi @caleb15 -- this is mostly due to the way we configure a Dockerized collector via environment variables: unfortunately, there's not a good way to extend that scheme to configuring multiple servers. Do you know of good patterns for configuring Dockerized services that might work for the collector?

**Comment by dullyouth** [comment]
The docker container has the option to read a config file. The config file can define multiple services.

mounting a pganalyze-collector.conf in the dockerfile should allow you to collect for multiple databases from a single container.

example pganalyze-collector.conf
```
[pganalyze]
#api_key = your_api_key

[server1]
#db_host = 127.0.0.1
#db_name = mydb, *
#db_username = myusername
#db_password = mypassword

#[server2]
#db_host = 127.0.0.1
#db_name = mydb, mydb2, mydb3
#db_username = myusername
#db_password = mypassword
#db_port = 5432
#aws_db_instance_id = your_rds_instance
#aws_region = us-west-2
#azure_db_server_name = your-azure-database
#gcp_project_id = your-gcp-project
#gcp_cloudsql_instance_id = your-cloudsql-database
```

**Comment by uhoh-itsmaciek** [comment]
@dullyouth yeah, that's a good point. We should probably document this as the official mechanism to do that, at least until we find something better.

**Comment by msakrejda** [comment]
This was addressed with [CONFIG_CONTENTS](https://github.com/pganalyze/collector/blob/main/CHANGELOG.md#0452------2022-08-31) in v0.45.2.
