### ISSUE TITLE
AWS Aurora/RDS log insight limitation

### ISSUE THREAD

**Issue by llivingstone** [pganalyze/collector#139]
Hi,

Currently, when using Aurora or RDS clusters with multiple instances failovers are a normal part of the ecosystem and therefore any replica of the Aurora or RDS cluster can be the reader or writer.

The collector currently has a limitation where if the cluster name is different from the instance ID you have to specify `aws_db_instance_id` in order to obtain LogInsights/Explain plans. Considering the above statement, this means the user would have to manually edit the `aws_db_instance_id` configuration for the cluster every time there is a failover event.

Could potentially using the `rds:DescribeDBInstances` action to determine the writer be a nice way to make finding the instance ID automated?

**Comment by lfittl** [comment]
@llivingstone Thanks for the request - we're reviewing whether we can improve this in the collector in the future (but this requires a bit of rework of how we interact with clusters in the collector).

**Comment by lfittl** [comment]
This has been implemented in the collector as of [version 0.45.1](https://github.com/pganalyze/collector/blob/main/CHANGELOG.md#0451------2022-08-12) (we now auto-detect the instance for the writer, and the reader in two node clusters).
