### ISSUE TITLE
Scan error on column index 0

### ISSUE THREAD

**Issue by psartini** [pganalyze/collector#14]
We get the following error messages from the collector:

`
2017/03/01 11:32:23 W [server1] Error collecting replication statistics: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string
2017/03/01 11:32:23 E [server1] Could not process database: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string
`

**Comment by lfittl** [comment]
@psartini Thanks for reporting - this was indeed a temporary bug in the 0.9.10 release.

We released 0.9.11 today which resolves this issue. Could you update the collector and see if it works now?

**Comment by lfittl** [comment]
Closing this for now due to inactivity. Please let us know if this is still a problem.
