### ISSUE TITLE
Success callback

### ISSUE THREAD

**Issue by jglapa** [pganalyze/collector#15]
Hi, 
would it be possible to add something like a  `success callback` feature?
In previous versions of the collector when it was executed with cron I always added monitoring to it eg. https://healthchecks.io/
Thanks to this when there was a problem with collector or it took longer that expected I would get notified that's something wrong.

With the new version where collector is executed as a daemon I'm lacking this monitoring feature. I would propose that you add a config option that would be a shell expression or a shell script that could be run on every successful run?

**Comment by lfittl** [comment]
@jglapa Interesting idea!

I wonder if you could check the modified time of the state file (typically at /var/lib/pganalyze-collector/state) and alert if its older than e.g. 15 minutes?

**Comment by jglapa** [comment]
From what I see the file `/var/lib/pganalyze-collector/state` is getting modified every run although the data is not submitted to pganalyze.

I'm currently troubleshooting the following problem:
* I have a postgresql 9.6 installation on AWS RDS
* I've configured everything as described in the manual
* I'm using the newest collector
* but when I run the collector with `--dry-run` I'm getting the following:
```
2017/04/21 15:07:25 V [xxx] Detected PostgreSQL Version 90601 (PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit)
2017/04/21 15:07:25 V [xxx] Found pganalyze.get_stat_statements() stats helper
2017/04/21 15:07:25 E [xxx] Error collecting pg_stat_statements
2017/04/21 15:07:25 E [xxx] Could not process database: pq: pg_stat_statements must be loaded via shared_preload_libraries
```

This must be an RDS issue since I've configured the `shared_preload_libraries=pg_state_statements` correctly in parameter group but psql shows `rdsutils`... ?, 
```
(xxx@xxx.amazonaws.com:5432) [test]  [] > \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_stat_statements | 1.4     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)


(xxx@xxx.amazonaws.com:5432) [test]  [] > show shared_preload_libraries;
 shared_preload_libraries
--------------------------
 rdsutils
(1 row)

(xxx@xxx.amazonaws.com:5432) [test]  [] > select * from pg_stat_statements ;
ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
Time: 165.208 ms
```


Anyhow with this issue in place the `/var/lib/pganalyze-collector/state` mtime is still getting changed although an error is raised.

**Comment by lfittl** [comment]
@jglapa Fair point - for the specific issue you are seeing, first check that you have restarted your RDS server (otherwise changes to shared_preload_libraries don't take effect). We've also sometimes seen problems where RDS has an internal problem, and typically updating to the next minor PostgreSQL release fixed that.

On the success callback - I'm currently thinking we just make it `--success-callback=/path/to/shell/script.sh`, which gets triggered once for each server, with the first and only argument being the name of the server (as per the collector config file). That sound reasonable?

**Comment by jglapa** [comment]
> `--success-callback=/path/to/shell/script.sh`

And how would we configure that? 
This would require changing collector startup scripts (upstart right now)?

I was more thinking about a new property in the `pganalyze-collector.conf` file. 

Passing the db config name when calling the script sound like a very good idea!

In my case I could either have 2 separate shell script( I have 2 db's) and simply ignore the passed parameter or have one script and make the distinction based on the parameter passed.
