### ISSUE TITLE
Support for AssumeRoleWithWebIdentity?

### ISSUE THREAD

**Issue by booleanbetrayal** [pganalyze/collector#180]
I have an EKS Fargate cluster using Amazon's recommended practice of [supply Role access to an EKS ServiceAccount annotation](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) in order to provision AWS access to a pod. I appear to have everything configured correctly and am seeing the AdmissionController do it's thing. Only problem is, it doesn't appear the PGAnalyze is able to leverage it:

```
Submitted compact activity snapshot successfully
Could not collect logs for server: could not collect logs: Error finding RDS instance: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Submitted compact activity snapshot successfully
```

Is there any plan to implement [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)? It appears to be supported in the [Go AWS SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.AssumeRoleWithWebIdentity).

**Comment by lfittl** [comment]
Hi @booleanbetrayal - thanks for opening this issue, I think its a good idea to add direct support for this.

That said, I'm wondering if you can utilize the environment variable based configuration to verify whether this works as intended today, without any code changes:

The SDK supports the same variables as the CLI (see https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#assume-role-with-web-identity at the end), so I think you can set the following:

* `AWS_ROLE_ARN`: The ARN of the role you want to assume.
* `AWS_WEB_IDENTITY_TOKEN_FILE`: The path to the web identity token file.

If I understand the AWS documentation correctly, you can simply set `AWS_WEB_IDENTITY_TOKEN_FILE` to `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`, and the `AWS_ROLE_ARN` to the correct role, and assuming you have the annotations set correctly, that should just work.

One more thing you might have to do is permit the `pganalyze` user to access the identity token file, as documented here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration

Let me know if that works, I'd be curious :)

**Comment by booleanbetrayal** [comment]
Actually, @lfittl - I'm wondering if the issue is in the creation of the provider chain via: https://github.com/pganalyze/collector/blob/master/util/awsutil/amazon.go#L56-L66

[According to the documentation](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#EnvProvider), `EnvProvider` only supports:

>  * Access Key ID: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY
>* Secret Access Key: AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY 

So maybe by explicitly configuring the provider chain for credentials creation, the legs are being cut out from some other automated WebIdentity provider support (if it even exists)?

**Comment by lfittl** [comment]
> Actually, @lfittl - I'm wondering if the issue is in the creation of the provider chain via: https://github.com/pganalyze/collector/blob/master/util/awsutil/amazon.go#L56-L66
> 
> [According to the documentation](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#EnvProvider), `EnvProvider` only supports:
> 
> > * Access Key ID: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY
> > * Secret Access Key: AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY
> 
> So maybe by explicitly configuring the provider chain for credentials creation, the legs are being cut out from some other automated WebIdentity provider support (if it even exists)?

Yeah, you might be right, looking at the code again.

I think its relatively straightforward to add this support, let me give that a try & will share a PR in a bit.

**Comment by booleanbetrayal** [comment]
Thanks @lfittl ! Not urgent, but appreciated!

**Comment by lfittl** [comment]
@booleanbetrayal Wasn't too much work :)

PR here: https://github.com/pganalyze/collector/pull/181

You can try this out by using the special Docker image `quay.io/pganalyze/collector:hotfix-aws-web-identity-support` that I just built - could you give this a try and see whether it works as expected?
