### ISSUE TITLE
Allow filter sensitive data from query logs

### ISSUE THREAD

**Issue by danbst** [pganalyze/collector#20]
Hi. We use a custom collector patch, that removes sensitive content from queries before sending logs to pganalyze server.

```
diff --git a/input/system/logs/parse.go b/input/system/logs/parse.go
index 01863e7..e71cbd1 100644
--- a/input/system/logs/parse.go
+++ b/input/system/logs/parse.go
@@ -211,6 +211,15 @@ func ParseAndAnalyzeBuffer(buffer string, initialByteStart int64, linesNewerThan
                // Generate unique ID that can be used to reference this line
                logLine.UUID = uuid.NewV4()

+               if strings.Contains(logLine.Content, "_encrypt"){
+                       //logger.PrintError("Censored encrypt line: %s", logLine.Content)
+                       logLine.Content = "--Censored Encryption Content;"
+               }
+               if strings.Contains(logLine.Content, "_decrypt"){
+                       //logger.PrintError("Censored decrypt line: %s", logLine.Content)
+                       logLine.Content = "--Censored Decryption Content;"
+               }
+
                logLines = append(logLines, logLine)
        }
```

Would be extremely cool if this would be supported by upstream, preferably with configurable filtered function names.

**Comment by lfittl** [comment]
@danbst You're in luck, we're actually about to release a PII filtering feature to solve this kind of scenario :)

To understand your use case - you only want to mask log lines that reference your decryption/encryption function, presumably because there is a key or sensitive data contained, correct?

**Comment by danbst** [comment]
yes, exactly! Function arguments contain sensitive data

**Comment by lfittl** [comment]
Hi @danbst!

I realized this was actually released but I haven't updated the issue. You can now filter sensitive log data using the `filter_log_secret` configuration parameter.

One recommended configuration would be the following:

```
filter_log_secret: credential, parsing_error, table_data, statement_parameter
```

This filters known parts of loglines that are credentials, as well as parsing errors, any output of table data and statement parameters.

If you don't use statement parameters but have your encryption keys directly in the query, it may be good to also add `statement_text` to the filter list.

Hope thats useful!
