### ISSUE TITLE
"collector --test-explain" does not seem to work

### ISSUE THREAD

**Issue by beyondbill** [pganalyze/collector#208]
I followed the [instruction](https://pganalyze.com/docs/explain/setup/amazon_rds/01_auto_explain_check) to set up EXPLAIN PLAN but the final testing step does not seem to work

Ran this
```
➜  ~ kubectl exec -n pganalyze-collector-staging -it pganalyze-collector-staging-86cfdc446d-zcmkk sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/go/src/github.com/pganalyze/collector $ ps
PID   USER     TIME  COMMAND
    1 pganalyz  5:53 /home/pganalyze/collector --statefile=/state/pganalyze-collector.state --no-log-timestamps
  116 pganalyz  0:00 sh
  123 pganalyz  0:00 ps
/go/src/github.com/pganalyze/collector $ /home/pganalyze/collector --test-explain
2021/10/15 14:13:31 I Running collector test with pganalyze-collector 0.40.0
/go/src/github.com/pganalyze/collector $ /home/pganalyze/collector --test-explain
2021/10/15 14:23:49 I Running collector test with pganalyze-collector 0.40.0
```

But still getting this after 30 min and several snapshot uploads
![image](https://user-images.githubusercontent.com/10553863/137507037-5457e90c-2b0b-43e4-a536-b9169105ea98.png)
![image](https://user-images.githubusercontent.com/10553863/137507706-1a580345-8f22-425d-9532-d9b7a15fa8fe.png)

**Comment by lfittl** [comment]
@beyondbill Are you still running into this issue? (I believe we may have also talked about this in a support ticket)

**Comment by beyondbill** [comment]
@lfittl Yeah I just reproduced the issue. Sorry for the late response. I was on leave. Also did not see a support ticket for this.

**Comment by lfittl** [comment]
@beyondbill Odd - could you open a new support ticket on this? It might be best if we do a screen share to debug the issue. (and welcome back from your leave!)

**Comment by uhoh-itsmaciek** [comment]
Closing this since `--test-explain` should work correctly--if you're seeing any issues here, please reach out to pganalyze support.
