### ISSUE TITLE
true:false vs 1:0

### ISSUE THREAD

**Issue by danielkucera** [pganalyze/collector#245]
Hi,
it is confusing to use in documentation value `true` if `false` doesn't represent opposite.
See here:
https://pganalyze.com/docs/explain/setup/log_explain/02_enable_log_explain

While setting `false` doesn't disable the feature because it is not "" nor `0`:
https://github.com/pganalyze/collector/blob/main/config/read.go#L62

Note that we are using kubernetes yaml, where we cannot use boolean values but only "true"/"false" as strings.

**Comment by uhoh-itsmaciek** [comment]
Thanks for bringing this up--I have a PR for a fix. Please let us know if that approach works for you.
