### ISSUE TITLE
Support Log Insights for Google Cloud AlloyDB for Postgres

### ISSUE THREAD

**Issue by premist** [pganalyze/collector#272]
Hello, 
I'm evaluating Google Cloud AlloyDB for Postgres, which is a fully PostgreSQL compliant database like Amazon Aurora. 

The basic installation of collector works fine, however collector is not picking up logs from Cloud Pub/Sub, probably because `resource.type` is different from Cloud SQL PostgreSQL.

Here is an example log entry payload.

```json
{
  "textPayload": "2022-05-20 05:39:01.827 UTC [2081]: [135-1] db=,user= LOG:  [g_vacuum.c:851]  Autovacuum worker memory: 65536(kb)",
  "insertId": "REDACTED",
  "resource": {
    "type": "alloydb.googleapis.com/Instance",
    "labels": {
      "location": "us-central1",
      "cluster_id": "REDACTED",
      "resource_container": "projects/REDACTED",
      "instance_id": "REDACTED"
    }
  },
  "timestamp": "2022-05-20T05:39:01.827876Z",
  "severity": "INFO",
  "labels": {
    "NODE_ID": "nfq2",
    "CONSUMER_PROJECT": "REDACTED"
  },
  "logName": "projects/REDACTED/logs/alloydb.googleapis.com%2Fpostgres.log",
  "receiveTimestamp": "2022-05-20T05:39:02.646346720Z"
}
```

Read through the codebase a bit, and I think [input/system/google_cloudsql/logs.go](https://github.com/pganalyze/collector/blob/main/input/system/google_cloudsql/logs.go#L77) can be modified in order to support AlloyDB.

**Comment by lfittl** [comment]
@premist Thanks for reaching out!

Yes, I think you are correct that this should be easy to support. Could you confirm which `log_line_prefix` setting you have active on the AlloyDB instance? (the `[g_vacuum.c:851]  Autovacuum worker memory: 65536(kb)` looks a bit non-standard, but that might just be extra debug output they provide)

**Comment by premist** [comment]
@lfittl I can't find a way to set `log_line_prefix`. Maybe it's Google's own autovacuum implementation that works on their distributed storage layer?

Attached screenshots for illustration purposes. 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/291078/169464443-15e3ac3c-d546-45a0-b838-158f7d61f7c2.png">


<img width="658" alt="image" src="https://user-images.githubusercontent.com/291078/169464318-f8185757-765c-4b0c-8833-ba7083186f1e.png">

**Comment by premist** [comment]
I made a small [tweak](https://github.com/premist/pganalyze-collector/commit/083b4057fd6ae60a85e389ee4f1c8faa3d206648) and trying to build and run collector to see if basic log transport functionality works.

**Comment by lfittl** [comment]
> @lfittl I can't find a way to set `log_line_prefix`.

Could you try running `SHOW log_line_prefix` on a Postgres connection to the database?

**Comment by premist** [comment]
Ah, that works! Here's an output.

```
%m [%p]: [%l-1] db=%d,user=%u 
```

**Comment by lfittl** [comment]
> Ah, that works! Here's an output.
> 
> ```
> %m [%p]: [%l-1] db=%d,user=%u 
> ```

Excellent, thanks!

The good news is, this is a supported log line prefix for the collector, so you should be able to get data flowing into pganalyze.

However, from your screenshot, it appears that Google's team has modified the Postgres log output logic a bit, since they are prefixing log messages with the source code file (e.g. `[analyze.c:830]`) for the autovacuum log in the above example.

This will cause a problem with our log handling, since the regular expressions we use for matching log lines won't match. We can customize this (probably in the GCP log handler), but it'll require a small patch (essentially I'm thinking we just strip the `[filename:line]` portion from the GCP log line before passing it to our parsing logic).

**Comment by gajus** [comment]
@lfittl When can we expect the official container to supper @premist changes?

**Comment by lfittl** [comment]
@gajus Just pushed up the required changes at #302 (testing welcome, note the new config settings) -- aiming to get that into the next, or next next, collector release.
