### ISSUE TITLE
update documentation for configuring docker version

### ISSUE THREAD

**Issue by oppianmatt** [pganalyze/collector#28]
The README describes how to run a dockerized collector and uses environment variables to configure it. But how do we configure a pganalyze-collector.conf as needed by insights? https://app.pganalyze.com/docs/guides/setup_log_insights_on_self_hosted_server

If we create a local conf and volume mount it where? And will that override any default conf file that is needed?

**Comment by mgood** [comment]
#29 may also be of interest since it's requesting the ability to configure everything via environment variables, so you wouldn't need to inject a config file when using Docker.

**Comment by lfittl** [comment]
@oppianmatt Is the database you're looking to monitor in the cloud (e.g. RDS), or an on-premise database?

If its on RDS, all you need to set is PGA_ENABLE_LOGS. If its on-premise, https://github.com/pganalyze/collector/commit/515202d833f3c1c143d330c494aaacd60d348be0 might be the fix (allowing you to mount a volume that has the log files, and then monitor that).

I'm also adding a TODO item here to update the documentation, as this is currently confusing to read when using the Docker container.

**Comment by lfittl** [comment]
This is no longer necessary, as we now automatically enable Log Insights if you are connecting to a supported endpoint (e.g. RDS)
