### ISSUE TITLE
Not all config options can be configured via env vars

### ISSUE THREAD

**Issue by szuliq** [pganalyze/collector#29]
Why some config options are being read from env vars and some are not?

I really liked the fact I can configure `collector` via env vars on Docker. The joy ended when I wanted to set `db_log_location`.

Please make all options configurable via env vars.

**Comment by LifeMoroz** [comment]
The same question.
Im using pg analyze with Docker-Compose and it is very painful to return on config-files

**Comment by mgood** [comment]
Agreed, it would be nice if the environment keys were derived automatically from the `ini` tags so that they were always in-sync.

I'd also like the ability to configure multiple dbs via the environment. That could be split into a separate issue if it adds too much complexity to implement at once. For example something like:
```
DB_HOST[foo]=foo.rds...
DB_HOST[bar]=bar.rds...
```

**Comment by lfittl** [comment]
This is all good feedback, and will give this some more thought how multiple DBs can be supported.

For the main issue initially reported (`db_log_location`) I pushed a fix yesterday (https://github.com/pganalyze/collector/commit/515202d833f3c1c143d330c494aaacd60d348be0) and will stamp a new release in the next few days.

Would it be useful if the regular config file format was accepted by the Docker container? (i.e. the full size config file as an env variable, or mounted in as a volume?)

**Comment by szuliq** [comment]
It already is accepted. I've mounted config file to `/home/pganalyze/` on
the container and it was picked up. As per multiple databases: for me
single db is enough. You can always set up multiple containers with
collectors if you have multiple dbs or use the file method if you really
want to.

pt., 30 lis 2018, 17:32: Lukas Fittl <notifications@github.com> napisał(a):

**Comment by lfittl** [comment]
@szuliq Good point, you are indeed correct that this already works :)

**Comment by lfittl** [comment]
Closing this since the `LOG_LOCATION` environment variable is now available in version 0.17.1.
