### ISSUE TITLE
Server names duplicated in UI when identically named hosts are monitored in the same organization

### ISSUE THREAD

**Issue by mikeizzy** [pganalyze/collector#297]
The “self-managed system ID” does not seem to be configurable: [collector/identify_system.go at 21ed66f04eea6cd310362650ee038bfb7d41023b · pganalyze/collector](https://github.com/pganalyze/collector/blob/21ed66f04eea6cd310362650ee038bfb7d41023b/config/identify_system.go#L81-L87) 

https://pganalyze.com/docs/collector/settings#server-connection-settings

> _"In-app names are based on hostname settings as determined during monitoring."_

This will be an issue if we wish to monitor identically named hosts in different environments, where their names will clash in the dropdown list (they will both appear, but it will be confusing which to select in the UI). The display name can be renamed but it would be great if this could be configured on the `.conf` file.

Is there a reason why this is not configurable in `pganalyze-collector.conf`, and can this be made to be differentiable?

**Comment by lfittl** [comment]
Hi @mikeizzy,

You can override the system ID by setting the `api_system_id` setting:

https://pganalyze.com/docs/collector/settings#additional-settings

Note that the system ID does serve an important function (it differentiates servers in the system, together with the scope and type), therefore be careful the tuple of id+scope+type is unique for each server.

The system ID is also used as the default for the name shown in the UI (as you discovered), but it doesn't update that name after creation. For that you'd have to go into the UI (or the API), as you noted.

I hope that helps! (we should probably document this better)

**Comment by mikeizzy** [comment]
Thanks [lfittl](https://github.com/lfittl), can we synthesise `scope` and `type`? What would be an example, e.g. `customHostname_someScope_someType`? If this is possible to synthesise it would satisfy our requirements.

**Comment by lfittl** [comment]
@mikeizzy Not sure I understand what you mean by synthesize - if you mean whether you can set them to arbitrary values, I would say yes for `scope` (as long as it stays consistent, it doesn't serve a particular function), but I would not set `type` to an arbitrary value (there is a fixed list of accepted type values). Hope that helps!

**Comment by mikeizzy** [comment]
Thanks, I think it's clear now. We'll try overriding the `PGA_API_SYSTEM_ID` as you've suggested.
