### ISSUE TITLE
fails to install on Ubuntu 18.04 LTS pganalyze-collector.postinst: start: not found

### ISSUE THREAD

**Issue by johntellsall** [pganalyze/collector#30]
it's a new EC2 instance created in AWS

# uname -a
Linux ip-10-10-11-20 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

> apt-get install -y pganalyze-collector

Reading package lists... Done
Building dependency tree
Reading state information... Done
pganalyze-collector is already the newest version (0.19.1).
0 upgraded, 0 newly installed, 0 to remove and 106 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up pganalyze-collector (0.19.1) ...
/var/lib/dpkg/info/pganalyze-collector.postinst: 46: /var/lib/dpkg/info/pganalyze-collector.postinst: start: not found
dpkg: error processing package pganalyze-collector (--configure):
 installed pganalyze-collector package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 pganalyze-collector
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by lfittl** [comment]
Thanks for the report!

Could you show which repository configuration you've used?

**Comment by johntellsall** [comment]
Sure! I'm happy to add info. 

```
# egrep '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/pganalyze_collector.list
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
/etc/apt/sources.list:deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu bionic-security main restricted
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu bionic-security universe
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu bionic-security multiverse
/etc/apt/sources.list.d/pganalyze_collector.list:deb [arch=amd64] https://packages.pganalyze.com/ubuntu/trusty/ stable main
```

**Comment by lfittl** [comment]
Could you try replacing `trusty` with `xenial`?

There are no official bionic packages yet, but xenial is systemd based (instead of trusty, which is upstart based), which should resolve the issue I believe.

**Comment by johntellsall** [comment]
@lfittl thank you so much!

The instructions are correct. I suggest updating them from "For Ubuntu 16.04 LTS" to "For Ubuntu 16.04 LTS or later versions" :)

I specifically chose 18.04 as it's an LTS release, and a year old, then was surprised when my blind cut and paste failed to install the tool.  Ah well.

Thanks so much for your help!
