### ISSUE TITLE
auto explain queries include statement secrets

### ISSUE THREAD

**Issue by sj26** [pganalyze/collector#31]
I noticed here:
https://github.com/pganalyze/collector/blob/master/logs/analyze.go#L34

that the remainder, the plan section, which includes _Query Text_, isn't treated as secret — but the full query text can include sensitive information. Should it be treated as a secret?

**Comment by lfittl** [comment]
@sj26 The plan and query text itself currently marked as "unidentified", see the test here:

https://github.com/pganalyze/collector/blob/master/logs/analyze_test.go#L3188

There is more work happening here to make the sharing of the explain plans safe even in the face of PII/PHI, and have a more correct mapping for the full plan output.

For now, if you have sensitive query text (or anything else that would show up in the explain plan), it would be recommended to not use auto_explain for these kinds of queries.

**Comment by lfittl** [comment]
Also, as an alternative, you can use this configuration, not however that we intentionally filter out all explain plans and query samples in that situation:

```
filter_log_secret: all
filter_query_sample: all
```

**Comment by sj26** [comment]
🙇

**Comment by lfittl** [comment]
This has been resolved in https://github.com/pganalyze/collector/pull/284
