### ISSUE TITLE
Helm chart repo

### ISSUE THREAD

**Issue by jalaziz** [pganalyze/collector#328]
With #273, the helm chart was added to this repo. However, it's not usable without a helm repository to install from.

The possibility of hosting the repo on packages.pganalyze.com was discussed in the PR. Other options include Github Pages or even a dedicated Github repo.

Github also has [helm repo support on the roadmap](https://github.com/github/roadmap/issues/122) but it doesn't appear to be scheduled yet.

**Comment by jalaziz** [comment]
Instead of hosting the helm chart repo via static site, Helm 3.8 supports OCI registries: https://helm.sh/docs/topics/registries/

This means that you should be able to use the GHCR, GCR, ECR, etc as the helm repo.

**Comment by ViktorTverdun** [comment]
+1 to this. I was also looking for the helm chart that can be installed from repo, but so far need to copy the source.
