### ISSUE TITLE
Link to example output broken

### ISSUE THREAD

**Issue by mgalgs** [pganalyze/collector#33]
The README contains the following link in the "Example output" section: https://gist.github.com/terrorobe/7103234

That link 404's for me.  Could be because it's a private gist, or just a bad link.

**Comment by lfittl** [comment]
Hi @mgalgs!

Thanks for the feedback - I think for now the best approach is to recommend the use of the `--dry-run` option, which will output the specific data for your database.

I've updated the README accordingly. Let me know if you have any more questions in this regard :)
