### ISSUE TITLE
Helm chart to deploy the collector on k8s

### ISSUE THREAD

**Issue by mazzy89** [pganalyze/collector#36]
Not sure if this could help here or it is out of the scope of the project. I've available a Helm chart for the collector that we use in prod. If it might be helpful here, I can create a PR for that. 

Ping here if you need that

**Comment by lfittl** [comment]
@mazzy89 Thanks for offering this - we'd definitely be interested in a Helm chart that you're already using.

PR sounds good, we can provide this together with the repository to make it easier for others to integrate :)

**Comment by jmvasquez-ddc** [comment]
@mazzy89  I would love to see your helm chart implementation. Did you create a PR for this?

**Comment by mazzy89** [comment]
Not yet. We use it internally but I would need to create a PR for this. I will wire it over the weekend.

**Comment by jmvasquez-ddc** [comment]
Hi @mazzy89, do you have any updates on this? Thanks!

**Comment by ViacheslavSavinkov** [comment]
Hey! Do you still need helm chart? I managed to make it and I think it can be shared with community with minimal enhancements.

**Comment by uhoh-itsmaciek** [comment]
@ViacheslavSavinkov sorry for the delayed reply. Yes, we'd love if you could contribute this. The [contrib directory](https://github.com/pganalyze/collector/tree/main/contrib) is probably the right place for that if you'd like to submit a pull request.
