### ISSUE TITLE
Make IdentifierMap cache TTL configurable

### ISSUE THREAD

**Issue by jlisthood** [pganalyze/collector#370]
It would be nice if we could configure the TTL for the identifier cache in util/awsutil/rds.go. My org is hitting many issues with RDS API throttling on DescribeDBInstances calls and the top contender is pganalyze collector by far.

Seemingly, pganalyze collector is calling the AWS API just to read information that it already knows, i.e. the RDS identifier, so the API calls seem to be doing no real work. 

Since we couldn't land on an optimization like the one in #349 , how do we feel about making the TTL for the cache configurable to the user? That way my org could set a higher TTL and reduce the API call frequency

**Comment by jlisthood** [comment]
Actually, I believe this is now not relevant with #369

**Comment by jlisthood** [comment]
@lfittl thanks for the #369, we are excited to try it out!

**Comment by lfittl** [comment]
@jlisthood Great timing, and thanks for opening that PR initially - we should have the updated collector packages (v0.48.0) with this fix out later tonight.
