### ISSUE TITLE
error on starting service

### ISSUE THREAD

**Issue by kmroz9** [pganalyze/collector#4]
Hello,
 I am getting this error while starting the service. 
"ERROR - 2016-07-22 21:42:55,764 Got an error during query execution
ERROR - 2016-07-22 21:42:55,764 permission denied for schema pganalyze"

Any idea what it is? 
I re-ran through all the instructions again. https://pganalyze.com/docs/install/amazon_rds/02_create_monitoring_user

**Comment by lfittl** [comment]
@kmroz9 That seems odd, can you verify that you ran these two commands:

```
REVOKE ALL ON SCHEMA public FROM pganalyze;
GRANT USAGE ON SCHEMA pganalyze TO pganalyze;
```

In addition, can you check if you did actually specify the `pganalyze` user as the username you are connecting with?

**Comment by lfittl** [comment]
Closing this question due to inactivity - please feel free to re-open or reach out to us at team@pganalyze.com if this is still a problem.
