### ISSUE TITLE
Mutex error after a few minutes of running

### ISSUE THREAD

**Issue by MichaelDanielTom** [pganalyze/collector#41]
Hey everyone, on Amazon Linux the collector will start up, and run fine, showing that activity and log data are successfully submitted for all log data. But then after around 5 minutes, the service fails with `fatal error: sync: unlock of unlocked mutex`, spits out a go stack trace, and then closes with `pganalyze-collector.service: main process exited, code=exited, status=2/INVALIDARGUMENT`.

A few other things to note: our setup ran fine with 2 databases connected in the `/etc/pganalyze-collector.conf`, and only started erroring when we went up to 4, adding 2 more. There didn't seem to be any memory pressure during all of this. There also seemed to be an error uploading to S3 citing something related to 'EOF' a minute or so before the mutex error - not sure if it's related.

**Comment by mrmuskrat** [comment]
I'm seeing the same issue on CentOS 6.1 with 3 databases in the config.

**Comment by lfittl** [comment]
Hi @MichaelDanielTom @mrmuskrat 

Thanks for your reports - this should be fixed in the next release (0.28.0)

Its currently building the release version for a final test, packages should be out tomorrow.

**Comment by lfittl** [comment]
As discussed, this should be fixed in 0.28.0 - I'm therefore closing the issue. Please let us know if you are still running into this.
