### ISSUE TITLE
Error to send snapshots

### ISSUE THREAD

**Issue by wandercunha** [pganalyze/collector#414]
Hi, 
I've been getting this "error" for two days now when sending snapshots. I have the latest version of the collector.

Successfully prepared S3 request - size of request body: 1.1152 MB
2023/04/27 12:41:35 E [server1] Could not process server: https://api.pganalyze.com/v2/snapshots/test giving up after 5 attempt(s)
2023/04/27 12:41:35 I [server1] Testing activity snapshots...

**Comment by seanlinsley** [comment]
Hi @wandercunha, thanks for the report. This should be working again.

**Comment by lfittl** [comment]
Closing this since this issue should be resolved (and was on the service side, not the collector side) - @wandercunha please let us know if you're still seeing any issues.
