### ISSUE TITLE
Missing image for v0.50.1

### ISSUE THREAD

**Issue by booleanbetrayal** [pganalyze/collector#431]
Noticing that there is no Docker image for the v0.50.1 release. Seems like these can sometimes lag the announcement. Is there a separate CI process that needs to be consolidated here?

**Comment by lfittl** [comment]
You are correct - the relevant step here is currently manual (see https://github.com/pganalyze/collector/blob/main/CONTRIBUTING.md#release), thus the slight delay.

This should be resolved now for this release (the manual step is completed).

Automating this is certainly on our list, but there is some security considerations around this that make it slightly more complicated - but we hope to find an approach that fixes that in the future.
