### ISSUE TITLE
Debian build uses EOL version

### ISSUE THREAD

**Issue by jawnsy** [pganalyze/collector#437]
The Debian package build is running `buster`, which [no longer receives security updates, as of June 30th, 2022](https://www.debian.org/releases/buster/): https://github.com/pganalyze/collector/blob/c1233a3b9fdb861ec0e1498d351ada0a4c19553c/packages/src/Dockerfile.build.deb-systemd#L1

**Comment by lfittl** [comment]
Good point - we've kept this low to avoid bumping up the minimum required glibc, but since `buster` is now EOL as you note, we should update this.
