### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by bdittmer** [pganalyze/collector#5]
For the docker container -- PG_API_KEY is actually PGA_API_KEY, PG_URL doesn't appear to work, ...

**Comment by bdittmer** [comment]
I'm still unable to get going...I'm using ansible to attempt to deploy the docker container to an existing server. My role looks like this:

```
---
- name: Pull image and run for dev
  docker:
    name: pganalyze
    image: pganalyze/collector:stable
    pull: always
    state: reloaded
    restart_policy: on-failure
    restart_policy_retry: 3
    env:
        PGA_API_KEY: "{{ pganalyze_api_key }}"
        DB_NAME: "{{ db_name }}"
        DB_HOST: "{{ db_host }}"
        DB_USERNAME: "{{ pg_analyze_db_user }}"
        DB_PASSWORD: "{{ pg_analyze_db_pass }}"
        AWS_ACCESS_KEY_ID: "{{ pganalyze_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ pganalyze_secret_access_key }}"
        AWS_DB_INSTANCE_ID: prod-db
```

and ```docker logs pganalyze``` output is: 

```
Doing initial collector test run...
ERROR - 2016-07-25 03:05:45,717 Failed to connect to database: ('communication error', gaierror(-2, 'Name or service not known'))
Doing initial collector test run...
ERROR - 2016-07-25 03:05:46,032 Failed to connect to database: ('communication error', gaierror(-2, 'Name or service not known'))
Doing initial collector test run...
ERROR - 2016-07-25 03:05:46,493 Failed to connect to database: ('communication error', gaierror(-2, 'Name or service not known'))
Doing initial collector test run...
ERROR - 2016-07-25 03:05:47,137 Failed to connect to database: ('communication error', gaierror(-2, 'Name or service not known'))
```

I can connect to the database fine from psql on the host it's deploying to.

**Comment by bdittmer** [comment]
Now I'm just frustrated -- the docs here, for the golang collector, reference using this docker container: https://hub.docker.com/r/pganalyze/collector/~/dockerfile/ 

__However__, that appears to be the old python collector that the docs also say isn't to be used with RDS.

**Comment by lfittl** [comment]
@bdittmer Apologies, you are indeed correct that the documentation is out of date.

You can find the correct Docker image here: https://quay.io/repository/pganalyze/collector?tag=latest&tab=tags

For pulling the correct reference would be "quay.io/pganalyze/collector:stable". Let me know if you still run into issues with that image.

Again sorry this was frustrating for you, documentation should be fixed tomorrow - everything will point to the Go-based collector then.

**Comment by bdittmer** [comment]
Great, thanks. I ended up installing the collector from package cloud in a container. I'll take a look at the official Docker image though.

**Comment by lfittl** [comment]
@bdittmer Ok, great - the packagecloud packages are the same version, so you're all set.

I've fixed the README here now, website documentation to be updated later in the day. Thanks for your patience!
