### ISSUE TITLE
/tmp space used by logs

### ISSUE THREAD

**Issue by DiegoDAF** [pganalyze/collector#53]
Hi, I'm using pga 0.22.0, and I have the /tmp partition without disk space free (I know, all about the part problem) 

It's posible reduce the log size?

![image](https://user-images.githubusercontent.com/8060124/83440278-30129400-a434-11ea-8846-4b3d12dc691a.png)
![image](https://user-images.githubusercontent.com/8060124/83440418-72d46c00-a434-11ea-9a16-380fd111d704.png)

Thanks a lot, 
Diego

**Comment by lfittl** [comment]
Hi @DiegoDAF,

This should be improved in recent collector versions - could you attempt upgrading to the latest release (0.29.0) and see whether this resolves the problem?

Thanks!

**Comment by uhoh-itsmaciek** [comment]
@DiegoDAF I'll close this now since we haven't heard from you--please let us know if you're still seeing issues.
