### ISSUE TITLE
Regarding SSO login

### ISSUE THREAD

**Issue by jahnavisana2812** [pganalyze/collector#552]
Hi,

We are using the paid scaled version of pganalyze, and I have enabled
the SSO feature to provide access to all organization members.
However, I'm having trouble figuring out how members should log in to
pganalyze, as the site prompts for sign-up when visiting
[app.pganalyze.com](http://app.pganalyze.com/).

Could you please assist with this issue?

Thank you.

**Comment by lfittl** [comment]
Hi @jahnavisana2812 - Please open a support ticket through the pganalyze application, or through https://pganalyze.com/contact

For context, this repository is for the collector software only, not for other pganalyze application questions.
