### ISSUE TITLE
No I/O statistics from Docker volume

### ISSUE THREAD

**Issue by teohhanhui** [pganalyze/collector#6]
Under https://github.com/pganalyze/collector/blob/35eadf33238441739488fabe6f3eb79e139ae3ce/README.md#docker-container-non-rds it says:

> Note: You can add -v /path/to/database/volume/on/host:/var/lib/postgresql/data in order to collect I/O statistics from your database, this requires that it runs on the same machine.

But I've done exactly that (substituting for the correct path, of course) and it doesn't work.

**Comment by lfittl** [comment]
I think that the fix for #6 should take care of this, but if it doesn't please reopen :)
