### ISSUE TITLE
0.63.0 broke size reporting for TimescaleDB hypertables

### ISSUE THREAD

**Issue by bdomars** [pganalyze/collector#654]
It seems the changes in:

https://github.com/pganalyze/collector/commit/550439b020db7c8e634d9f3486ec68696b0c072a#diff-89c88e46957c7be3a80002749ee13e4611914aff1acf0eb5e27d05b119e3b98aR34

broke size reporting for TimescaleDB hypertables.

We're using TimescaleDB extensively and after an update of one of our clusters we noticed that size was no longer reported correctly for hypertables.

I guess for some reason pganalyze-collector does not find the partitions of these tables?

**Comment by seanlinsley** [comment]
Hi @bdomars, thanks for the report. I assume in your case you have [`ignore_schema_regexp`](https://pganalyze.com/docs/collector/settings#schema-filter-settings) set to ignore the hypertables?

We could add back the `pg_inherits` part of the query, but have it only aggregate the table size for child partitions matching `ignore_schema_regexp`. Thoughts @lfittl?

**Comment by bdomars** [comment]
Hi @seanlinsley

Indeed we had `ignore_schema_regexp: "_timescaledb_internal.*"`.

But we have ~45,000 tables in that schema and If I remove that ignore statement pganalyze-collector will refuse to send  schema information.

```
Too many tables: got 45041, but only 5000 can be monitored per server; schema information will not be sent
```

Not sure we'd even be interested in seeing these partitions in pganalyze, but the whole size of a hypertable is nice to have.
