### ISSUE TITLE
Collect system information when used with Docker

### ISSUE THREAD

**Issue by teohhanhui** [pganalyze/collector#7]
e5dc7756741c2d04f524bf2baf9028958f0f9fc3 disabled it.

Perhaps there can be an environment variable to control this?

**Comment by lfittl** [comment]
Good point - an env variable is probably the way to go, since a decent portion of users use the Docker image to monitor a remote host.

I'll see that we add it this week - thanks for the report :)

**Comment by lfittl** [comment]
@teohhanhui Just pushed https://github.com/pganalyze/collector/commit/dd38e813718513aa24aee0156f62dde6d859f228 that adds PGA_ALWAYS_COLLECT_SYSTEM_DATA for this purpose.

The docker container is pushed up at quay.io/pganalyze/collector:latest - let me know how it goes :)

**Comment by teohhanhui** [comment]
@lfittl Are you sure it's pushed? Because I see the last modified date on quay.io as August 16th.

**Comment by lfittl** [comment]
@teohhanhui I forgot to reply here - could you check again?

Make sure the docker tag is `quay.io/pganalyze/collector:latest` (any repository on Docker Hub instead of Quay.io is out of date and should not be used)

**Comment by teohhanhui** [comment]
Yes, it's been working for us.

**Comment by lfittl** [comment]
Excellent - thanks for the update!
