### ISSUE TITLE
Failed to fetch deb

### ISSUE THREAD

**Issue by oppianmatt** [pganalyze/collector#8]
Followed instructions. After adding:

```
deb https://packages.pganalyze.com/ubuntu/trusty/ stable main
```

To apt sources, apt then fails with:

```
W: Failed to fetch https://packages.pganalyze.com/ubuntu/trusty/dists/stable/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
```

Looking at that file, seems to be only `binary-amd64` and no `binary-i386`

**Comment by oppianmatt** [comment]
Note that it fetches the 64bit ones fine and my arch is 64 bit:


```
...
Hit https://packages.pganalyze.com stable InRelease
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en_GB
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en
Hit https://packages.pganalyze.com stable/main amd64 Packages
Fetched 4,227 kB in 2s (1,804 kB/s)
W: Failed to fetch https://packages.pganalyze.com/ubuntu/trusty/dists/stable/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
# arch
x86_64
```

**Comment by oppianmatt** [comment]
fix is to specify the arch as described here http://askubuntu.com/questions/743814/unable-to-find-expected-entry-main-binary-i386-packages-chrome

so the full line reads:

```
deb [arch=amd64] https://packages.pganalyze.com/ubuntu/trusty/ stable main
```


Instructions here need to be updated: https://app.pganalyze.com/databases/4570/install/02_installing_the_collector

**Comment by lfittl** [comment]
@oppianmatt Interesting - I wonder why its not picking this up correctly on its own (it does here).

Do you run inside a virtual machine / anything that might confuse the architecture detection there? (we only support 64-bit on the packages)

**Comment by lfittl** [comment]
This is now the default in the docs - even though I haven't found out the root cause of why this happens on 64-bit systems, it doesn't hurt to make the architecture explicit.

Thanks again for reporting this and sharing the fix!
