### ISSUE TITLE
Feature Request: Allow 'db_log_location' to take wildcard expressions

### ISSUE THREAD

**Issue by khanhibus** [pganalyze/collector#83]
I have a use case in which our postgres servers are logging both csv and stderr logs to the same location. The csv logs are forwarded to our local ELK stack for analysis. It would be tremendously helpful if the 'db_log_location' parameter could take a wildcard path such as:

- `/path/to/log/*.log`

The reason for this request is that pganalyze-collector is ingesting both the csv and stderr logs. When looking at the Log Insights view, I am seeing both stderr and csv logs and suspect that is causing the Query Performance EXPLAIN Plans to not work. I have been running the on-premise version of pganalyze for a year and have yet to see any EXPLAIN Plans. 

Thank you!

**Comment by lfittl** [comment]
Hi @khanhibus - Thanks for the feedback, we're reviewing whether we can add this functionality.

If you'd like to get more direct help on the issue with your setup, please email support@pganalyze.com so we can review this in detail.

**Comment by uhoh-itsmaciek** [comment]
@khanhibus the change in #146 is not exactly what you were asking for, but I believe it should handle your use case. Please let us know if this does not work for you. Thanks!
