### ISSUE TITLE
Container running as root

### ISSUE THREAD

**Issue by JordanP** [pganalyze/collector#87]
Hi,
Is there a reason with the container is running as root ?

It looks like the Dockeerfile (https://github.com/pganalyze/collector/blob/master/Dockerfile#L4) is adding a user but no "USER" directive, that user is not actually used.

**Comment by JordanP** [comment]
Hum, actually it's using gosu. Why not just use "USER" in the Dockerfile. Problem is, anybody that can "exec" into the container is actually "root".

**Comment by lfittl** [comment]
@JordanP I think this is mostly for historic reasons, since Docker didn't always support running the container as non-root. We'll review whether we can move away from the `gosu`-based approach, and instead use the `USER` command.

We would of course also welcome a patch for this, if you'd like.

**Comment by lfittl** [comment]
@JordanP FYI, we have a test image available at #174 that uses `USER` instead of gosu for the privilege drop. It would be great if you can give that a look and see whether it works for your environment.

**Comment by lfittl** [comment]
Closing based on #174 being merged.
